[package]
name = "avatar-cli"
version = "0.2.0"
authors = [ "Andres Correa Casablanca <castarco@coderspirit.xyz>" ]
edition = "2018"

[dependencies]
serde_yaml = "0.8"

  [dependencies.serde]
  version = "1.0"
  features = [ "derive" ]

[profile.release]
codegen-units = 1
lto = true
