---
stages:
  - boilerplate_checks

boilerplate_checks:
  stage: boilerplate_checks
  image: 'node:14-buster'
  tags: [docker]
  except:
    refs:
      - master
  script:
    - 'cd "${CI_PROJECT_DIR}/cx"'
    - 'npm install'
    - 'npm run lint'
    - |
      PATH="${CI_PROJECT_DIR}/cx/node_modules/.bin:${PATH}" \
      ./src/scripts/git_checks.ts
