---
stages:
  - boilerplate_checks
  - test
  - build_release
  - publish

boilerplate_checks:
  stage: boilerplate_checks
  image: 'node:14-buster'
  except:
    refs:
      - dev
      - main
      - /^v[0-9]+\.[0-9]+\.[0-9]+$/
  script:
    - 'cd "${CI_PROJECT_DIR}/cx"'
    - 'npm install'
    - 'npm run lint'
    - './node_modules/.bin/ts-node ./src/scripts/git_checks.ts'

test:
  stage: test
  image: 'rust:1.45-stretch'
  except:
    refs:
      - dev
      - main
      - /^v[0-9]+\.[0-9]+\.[0-9]+$/
  script:
    - rustup component add clippy
    - cargo clippy

build_release:
  stage: build_release
  image: 'rust:1.45-stretch'
  except:
    refs:
      - /^v[0-9]+\.[0-9]+\.[0-9]+$/
  only:
    refs:
      - main
  script:
    - cargo build --release
    - strip ./target/release/avatar
  artifacts:
    expire_in: never
    name: "linux-binary-release-$CI_COMMIT_SHA"
    paths:
      - ./target/release/avatar

gitlab_publish:
  stage: publish
  image: 'node:14-buster'
  except:
    refs:
      - /^v[0-9]+\.[0-9]+\.[0-9]+$/
  only:
    refs:
      - main
  script:
    - 'cd "${CI_PROJECT_DIR}/cx"'
    - 'npm install'
    - './node_modules/.bin/ts-node ./src/scripts/gitlab_publish.ts'

crates_publish:
  stage: publish
  image: 'rust:1.45-stretch'
  except:
    refs:
      - /^v[0-9]+\.[0-9]+\.[0-9]+$/
  only:
    refs:
      - main
  variables:
    CARGO_TOKEN: $CARGO_TOKEN
  script:
    - cargo login ${CARGO_TOKEN}
    - cargo publish --no-verify

include:
  # See https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
  # See https://gitlab.com/gitlab-org/gitlab-foss/blob/master/lib/gitlab/ci/templates/Security/SAST.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
