---
stages:
  - git_checks

git_checks:
  stage: git_checks
  image: 'node:14-buster'
  tags: [docker]
  script:
    - 'cd "${CI_PROJECT_DIR}/cx"'
    - 'npm install'
    - |
      PATH="${CI_PROJECT_DIR}/cx/node_modules/.bin:${PATH}" \
      ./src/scripts/git_checks.ts
